### ISSUE TITLE
Estimators need to (optimally) return convergence values

### ISSUE THREAD

**Issue by franknoe** [markovmodel/thermotools#10]
Iterative estimators such as WHAM etc must be able to return information about the convergence, i.e. the max-error history. It would also be useful to (optionally) access the likelihood history.

We have something like this for msmtools.estimation.transition_matrix (although that could be improved too)

**Comment by cwehmeyer** [comment]
WHAM and dTRAM now give (optional) access to the max-error and loglikelihood history via the arguments `err_out` and `lll_out` (output every `*_out` steps, default=0) in their `estimate()` functions.

Is that sufficient to close this issue?

**Comment by franknoe** [comment]
yes

Am 18/11/15 um 16:48 schrieb Christoph Wehmeyer:

> WHAM and dTRAM now give (optional) access to the max-error and 
> loglikelihood history via the arguments |err_out| and |lll_out| 
> (output every |*_out| steps, default=0) in their |estimate()| functions.
> 
> Is that sufficient to close this issue?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/thermotools/issues/10#issuecomment-157755072.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
