### ISSUE TITLE
Send 0.1.10 to conda-recipes?

### ISSUE THREAD

**Issue by rmcgibbo** [markovmodel/thermotools#23]
The 0.1.9 release is still broken in conda-recipes because of #19. Can you send the next release to conda-recipes when you get a chance?

**Comment by franknoe** [comment]
@cwehmeyer

Am 24/11/15 um 08:52 schrieb Robert T. McGibbon:

> The 0.1.9 release is still broken in conda-recipes because of #19 
> https://github.com/markovmodel/thermotools/pull/19. Can you send the 
> next release to conda-recipes when you get a chance?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/thermotools/issues/23.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
