### ISSUE TITLE
Avoid cryptic symbols in API

### ISSUE THREAD

**Issue by franknoe** [markovmodel/thermotools#7]
Many API functions have functions named after specific symbols used in a paper. Since there is no unique or even agreed-upon way of using symbols for these equations, I would rather use brief terms / words in most cases.

Examples in dTRAM

```
    'set_lognu',
    'iterate_lognu',
    'iterate_fi',
    'get_pk',
    'get_p',
    'get_fk',
```

**Comment by cwehmeyer** [comment]
So, in this style?

`set_lognu` -> `initialize_log_lagrangian_multipliers`
`iterate_lognu` -> `update_log_lagrangian_multipliers`
`iterate_fi` -> `update_ground_state_free_energies`
`get_pk` -> `estimate_all_transition_matrices`
`get_p` -> `estimate_single_state_transition_matrix`
`get_fk` -> `get_thermodynamic_free_energies`

**Comment by franknoe** [comment]
Maybe a bit briefer (the name doesn't need to tell the full story, it 
just needs to be recognizable)
||

|set_lognu| -> |init_lagrangian_mult|
|iterate_lognu| -> |update_lagrangian_mult|
|iterate_fi| -> |update_conf_energies|
|get_pk| -> |estimate_transition_matrices|
|get_p| -> |estimate_transition_matrix|
|get_fk| -> |get_therm_energies|

Am 04/10/15 um 08:02 schrieb Christoph Wehmeyer:

> So, in this style?
> 
> |set_lognu| -> |initialize_log_lagrangian_multipliers|
> |iterate_lognu| -> |update_log_lagrangian_multipliers|
> |iterate_fi| -> |update_ground_state_free_energies|
> |get_pk| -> |estimate_all_transition_matrices|
> |get_p| -> |estimate_single_state_transition_matrix|
> |get_fk| -> |get_thermodynamic_free_energies|
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/thermotools/issues/7#issuecomment-145320471.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
